### ISSUE TITLE
Selecting portrait orientation isn't reflected in the submitted bounding box

### ISSUE THREAD

**Issue by mojodna** [fieldpapers/fieldpapers#10]
Selecting "portrait" changes the widget, but the bounding box needs to be dragged in order to update the hidden fields that are `POST`ed back to the server.  This results in portrait atlases with landscape-style bounding boxes.

**Comment by sconnelley** [comment]
https://github.com/fieldpapers/fp-web/commit/544dc40b56874650c1a0f6ad190d1f95bf37b3c3#diff-6bbda18c76165410f1e754640955d452R190
