### ISSUE TITLE
Twitter URL Link Missing

### ISSUE THREAD

**Issue by mataharimhairi** [fieldpapers/fieldpapers#107]
There is twitter link provided while the Atlas is Rendering:

If it takes more than an hour, check http://twitter.com/fieldpapers for system status updates, and email us at help[at]fieldpapers.org if your atlas is stuck.

However when it is clicked, it takes you to this page where it appears to be missing:

http://stamen-fieldpapers-dev.herokuapp.com/atlases/@fieldpapers%20on%20Twitter

The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.

**Comment by mojodna** [comment]
Good catch, thank you.
