### ISSUE TITLE
Making a Letter Portrait Map Failing 

### ISSUE THREAD

**Issue by mataharimhairi** [fieldpapers/fieldpapers#109]
Trying to make a map in the Letter Portrait Landscape orientation is failing.

**Comment by mojodna** [comment]
This and #106 are artifacts of #89, which I'm on track to finish and deploy tomorrow.  In the meantime, I've been periodically restarting the task server (which is a terrible solution and I'm looking forward to not doing it any longer).

**Comment by mataharimhairi** [comment]
@mojodna Thanks for the update! Will be doing a bit more testing earlier this week to assist with any bugs.

**Comment by mojodna** [comment]
The flakiness has been resolved by switching to the task server.
