### ISSUE TITLE
getlatlon.com no longer exists

### ISSUE THREAD

**Issue by mojodna** [fieldpapers/fieldpapers#11]
We should suggest an alternative on the Canned Atlas form builder.

/cc @sconnelley

**Comment by lyzidiamond** [comment]
We should use this one from @springmeyer! http://dbsgeo.com/latlon/

**Comment by mojodna** [comment]
Good call!  Coming to you soon in a pending commit!

**Comment by springmeyer** [comment]
cool, for ref it lives over at https://github.com/springmeyer/latlon
