### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by severinmenard** [fieldpapers/fieldpapers#117]
Let comments  on Transifex regarding this string because I do not understand what it really describes, but I did not get an answer yet.

String:
¨Reworking of snapshot uploads is in progress; availability will increase over time."

Comments:
What does reworking mean here? And what kind of availability will increase over time?

**Comment by mojodna** [comment]
Ah, that's an outdated string from the alpha when I'd largely disabled uploading.  I just synced the strings, so it should have disappeared.

Reworking meant that we moved from using a single Python process running under Celery that assembled a single atlas at a time to a more modular process (using [fp-tasks](https://github.com/fieldpapers/fp-tasks)) that generates a page at a time and then merges them together.
