### ISSUE TITLE
Shapefile export link does nothing

### ISSUE THREAD

**Issue by danrademacher** [fieldpapers/fieldpapers#118]
Or, well, it scrolls me to the top of the page. As here:
http://fieldpapers.org/atlases/drmcwagx#

Under the "Export Data"

this is a minor feature in any case

**Comment by almccon** [comment]
So do not plan to support shapefile export anymore, and instead encourage use of GeoJSON? Asking because of https://twitter.com/ahasan4u/status/617195256228884481

**Comment by mojodna** [comment]
Correct.  Anything that consumes Shapefiles should also consume GeoJSON (which can be created without relying on an external library).
