### ISSUE TITLE
Page updates reset atlas providers

### ISSUE THREAD

**Issue by mojodna** [fieldpapers/fieldpapers#125]
The atlas's provider is OSM, but the associated pages all include both overlays.

(This is the typical cause of timed-out atlases, as the GADM overlay 404s outside the Philippines.)

**Comment by mojodna** [comment]
@sconnelley I could use some eyes on this to help figure out how this could happen.  See `atlas.rb`.

**Comment by sconnelley** [comment]
@mojodna do you have an example link?

**Comment by mojodna** [comment]
It's a private atlas (which could be a clue).  I've Slacked you the ID.

**Comment by mojodna** [comment]
I'm pretty sure that this was intentional--the reason it was going into Sentry was that the process timed out (either because one of the upstreams was having problems and/or returning 404s (which the GADM overlay does when you're outside its coverage)).

The actual issue is the inverse: when a page is updated by the task server (using an HTTP callback), it inadvertently resets the `provider` value because neither overlay is "set" during the update.
