### ISSUE TITLE
Large atlases are prone to double submission

### ISSUE THREAD

**Issue by mojodna** [fieldpapers/fieldpapers#126]
Saw this on a 501 page atlas (`ace7sxwy`).  Even if all of those pages were created, it's likely that the merge task would have timed out.

@dalekunce what are the largest atlases you guys are prone to create?  I'd like to impose an upper limit on size but I want to ensure that it's large enough to not cause trouble.

**Comment by quincylvania** [comment]
Now tracking atlas page limit at #286
