### ISSUE TITLE
Enhancement: keeping the FP atlas extent when clicking on + or -

### ISSUE THREAD

**Issue by severinmenard** [fieldpapers/fieldpapers#146]
Related to https://github.com/fieldpapers/fieldpapers/issues/145, it would be better if, once the user chose the wanted area for his atlas, that + and - are used to add/remove rows or columns in the atlas rather than adding/removing a new row or column of the same size (and therefore modifying the extent of the atlas). This would spare a lot of consecutive resizing actions to the user. 
Indeed, when they start, users know what area they want to cover, so this should be the first step. Second step is DIVIDING this area into rows and columns.

**Comment by sconnelley** [comment]
nice idea!

**Comment by ian-ross** [comment]
This should be covered by the new page composer UI in https://github.com/fieldpapers/fp-web/pull/23 which has this "division" behaviour for adding rows and columns.

**Comment by ericsoco** [comment]
@ian-ross great. Does that mean we should close this issue, or is there a finer point here that still needs to be tracked separately? (I'm coming on from Stamen briefly to help close some issues and still getting ramped up.)

**Comment by ian-ross** [comment]
If you can shelve these for just a few days, we should have a demo site up that will show the possibilities of the new interface, and that should make it easier to decide which of these are still relevant.  I'm hoping to have it all set up by Wednesday evening.
