### ISSUE TITLE
Atlas creation results in an application error when UTM Grid enabled

### ISSUE THREAD

**Issue by danrademacher** [fieldpapers/fieldpapers#15]
Here's what I did:

1. Zoomed to my neighborhood.
2. Added some pages and changed the base map:
![image](https://cloud.githubusercontent.com/assets/1423200/6788216/4b1dd262-d155-11e4-889d-13b7facca4bd.png)

3. Entered description:
![image](https://cloud.githubusercontent.com/assets/1423200/6788225/57813800-d155-11e4-96d9-5b53cf4c66aa.png)

4. Selected "Add a UTM Grid" and clicked "Finished!":
![image](https://cloud.githubusercontent.com/assets/1423200/6788299/a8ad0e84-d155-11e4-9a9b-5fff33e2bee2.png)

5. Got an error:
![image](https://cloud.githubusercontent.com/assets/1423200/6788197/279be64e-d155-11e4-96b3-62ecad5e4e80.png)

When I did the same steps without clicking on "Add a UTM grid overlay to each map?", it worked fine.

**Comment by sconnelley** [comment]
Fixed in 96853f74455663f4e510d6798fcac7be19abd17a
