### ISSUE TITLE
map viewport is unnecessarily small

### ISSUE THREAD

**Issue by danstowell** [fieldpapers/fieldpapers#150]
while on the "make" page, the map viewport is about 50% of the screen width (on my laptop). This is wasteful because the whitespace on each side means I have to do much more zoom-click-zoom-click-zoom-click to select the area I want

**Comment by ian-ross** [comment]
There's a PR in to fix this, along with some other UI interaction issues: https://github.com/fieldpapers/fp-web/pull/23

**Comment by ian-ross** [comment]
This issue should be fixed or rendered obsolete by https://github.com/fieldpapers/fp-web/pull/23: if anyone thinks it's still a problem, please reopen this issue!
