### ISSUE TITLE
No thumbnails at atlas gallery page

### ISSUE THREAD

**Issue by danrademacher** [fieldpapers/fieldpapers#16]
http://stamen-fieldpapers-dev.herokuapp.com/atlases

![image](https://cloud.githubusercontent.com/assets/1423200/6789859/bd6e88a6-d160-11e4-88fe-389f0affc56b.png)

**Comment by mojodna** [comment]
[`GeneratePDFJob`](https://github.com/fieldpapers/fp-web/blob/master/app/jobs/generate_pdf_job.rb) needs to generate thumbnails as part of processing.

**Comment by mojodna** [comment]
@sconnelley what are your thoughts about using static Leaflet views for these instead of images?  Would there be too many?

**Comment by sconnelley** [comment]
Went ahead and converted images to static leaflet maps, [commit](https://github.com/fieldpapers/fp-web/commit/52c10f12336a9f2e4376540418e4782d1cf6b15b).
Seems to run okay.
Had to fork `leaflet-rails` gem, to pass in map options so we can hide the zoom controls and disable map interactions.  The fork is [here](https://github.com/stamen/leaflet-rails)

**Comment by mojodna** [comment]
Hot!
