### ISSUE TITLE
Get FP running on Edison

### ISSUE THREAD

**Issue by mojodna** [fieldpapers/fieldpapers#168]
Possibly Yocto (default Edison distribution).  That the FP components already run out of Docker contains is a start, although getting the networks set up still needs to be sorted and most kernels for the Edison are 32-bit (https://communities.intel.com/thread/57334?tstart=0).

/cc @dalekunce

**Comment by quincylvania** [comment]
Closing as stale. Let us know if this is still desirable for some reason.
