### ISSUE TITLE
Looks like we have to update the "history" on the about page again

### ISSUE THREAD

**Issue by almccon** [fieldpapers/fieldpapers#172]
![screen shot 2015-06-23 at 1 38 05 pm](https://cloud.githubusercontent.com/assets/1212178/8316631/2d2f9326-19ad-11e5-998f-77c6d3df3c5f.png)

"The current version of Field Papers was completely rewritten and relaunched in May 2015, with support from X, Y, Z..."

**Comment by mojodna** [comment]
Duplicates #124

(yes)
