### ISSUE TITLE
Feature request: Edit in remote

### ISSUE THREAD

**Issue by rmikke** [fieldpapers/fieldpapers#177]
Would it be possible to add "Edit in remote" button, working just like an option in OSM Edit menu, i.e. opening JOSM or Merkaator with apropriate map fragment and FP as background image?

**Comment by mojodna** [comment]
Done with w/ JOSM per #96 

Can you point to Merkaator docs for doing this same thing?

**Comment by rmikke** [comment]
AFAIK What works with JOSM will work with Merkaator - they use the same "remote control" system of daemon listening on specific port.

**Comment by mojodna** [comment]
Ah, excellent. Do most Merkaator users know this?

**Comment by rmikke** [comment]
Honestly, no idea. But everywhere there is a "remote edit" option it is described as "for JOSM or Merkaator" so I guess the answer is yes :D
