### ISSUE TITLE
"Download PDF" link goes to same page

### ISSUE THREAD

**Issue by danrademacher** [fieldpapers/fieldpapers#18]
![image](https://cloud.githubusercontent.com/assets/1423200/6789976/8d649d52-d161-11e4-9803-c049e8e5f29c.png)

Just reloads the page:
http://stamen-fieldpapers-dev.herokuapp.com/atlases/5bpeooiv

Should prompt me to download a PDF

**Comment by sconnelley** [comment]
Not sure why PDF's aren't being made but for the time being I am hiding the button if there is no `pdf_url`.
![image](https://cloud.githubusercontent.com/assets/565486/6855840/0f1a816e-d3d2-11e4-9196-2c790e519a2e.png)

**Comment by danrademacher** [comment]
Is there another way to print the atlas? That's what's got me confused -- kind of a big blocker if downloading the PDF is the only way to print, but I might be missing a big print button...

**Comment by sconnelley** [comment]
Was there a "big print button" on fieldpapers.org?

**Comment by sconnelley** [comment]
Also, at the present moment, I have no way to update the Heroku app.

**Comment by danrademacher** [comment]
There wasn't a big print button that I could find. On either one. So downloading PDF is the road to printing. and not working -- I was hoping the link was just wrong but if the PDF is not getting generated, then that's a blocker for @mojodna

**Comment by sconnelley** [comment]
Hiding download button if no PDF url

**Comment by mojodna** [comment]
Other things that need doing related to this:

- [ ] debug PDF generation on Heroku (this was working fine locally, but the Docker gymnastics may be problematic)
- [ ] mark page / atlas as having been printed (`composed_at`)
- [ ] update atlas progress after each page
- [ ] display "rendering..." interstitial (with progress bar) if the PDF hasn't been created yet

**Comment by mojodna** [comment]
PDFs are being generated correctly, but they're not being uploaded to `staging.files.fieldpapers.org` (per the Heroku configuration).
