### ISSUE TITLE
I need help with a translation

### ISSUE THREAD

**Issue by Michael21011** [fieldpapers/fieldpapers#181]
Hi.
Please, could someone describe a meaning of word "canned"  (example: Canned Atlases)?

Thanks in advance!

**Comment by mojodna** [comment]
Pre-defined, where many of the attributes of the atlas have been determined ahead of time and it becomes possible to just print it without having to make any decisions about it.

Does that help?

**Comment by Michael21011** [comment]
@mojodna Could you please provide some synonyms for Canned Atlases? Is "Pre-defined" a synonym for "Canned"?

**Comment by mojodna** [comment]
Pre-defined
Pre-configured
Preset

(sorry, on vacation)

**Comment by donalhunt** [comment]
@Michael21011 has your query been answered? Can this issue be closed?

**Comment by Michael21011** [comment]
@donalhunt  I cannot find where this words are used on website.
