### ISSUE TITLE
List all atlases / snaphots (only) created by the logged-in account

### ISSUE THREAD

**Issue by severinmenard** [fieldpapers/fieldpapers#186]
Seems creating atlas while connected does not provide afterwards the possibility to access a list of the atlas created with the account. The only way to find previous atlas (if too old for the recent activity) seems to be bookmarking the page, what actually really limits the interest of logging in.

**Comment by mojodna** [comment]
Agreed.  This should be one of the main reasons for logging in.

**Comment by dalekunce** [comment]
putting these on a slippy map would be very helpful

**Comment by mojodna** [comment]
https://github.com/fieldpapers/fp-web/blob/master/app/controllers/atlases_controller.rb#L11

^^ figure out how to change this scope to be a username and then link to it.

**Comment by mojodna** [comment]
Talk to @alecburch about making the map bigger.

**Comment by ericsoco** [comment]
Will need to allow viewing both only logged-in viewer's content and everyone's content, probably as a toggle between the two somewhere. Also a list/count of viewer's content.

**Comment by ericsoco** [comment]
Ok, so the way I've solved this in https://github.com/fieldpapers/fp-web/pull/25 is by creating a `username` scope and using it in a number of places. This ^^ PR adds the ability to view all content (atlases & snapshots), just your content, or any particular user's content. Content privacy is still respected, and the concept of "your" content goes away when not logged in.

Will close this issue once the PR is in.

**Comment by mojodna** [comment]
This has been merged!
