### ISSUE TITLE
Add paper size selector

### ISSUE THREAD

**Issue by danrademacher** [fieldpapers/fieldpapers#19]
One of the key new features in field Papers is that we need to let people choose other paper sizes. I think @mojodna solved this through rendering the atlases as HTML pages, much more flexible for paper size, but I'm not seeing a page selector in the creation process and due to #18, I can't see if the PDF download function gives me a chance to change size.

Do you know how we select other paper sizes?

**Comment by sconnelley** [comment]
Does the original fieldpapers have the option to select paper sizes?  If not, is selecting a paper size a one time thing, like selecting orientation?

**Comment by danrademacher** [comment]
No it doesn't, but addition additional paper sizes is one of the three key improvements we're making (the others being increased stability/reliability and internationalization. Those second two we've got going, and I know @mojodna had made substantial progress on a much more flexible method of sizing the atlases, but obviously that's not wired up.

**Comment by sconnelley** [comment]
paper selector in
![image](https://cloud.githubusercontent.com/assets/565486/6878733/37b2c720-d4b9-11e4-9a64-736f71cdb20c.png)

**Comment by mojodna** [comment]
We need to test scanning of these to ensure that it works end-to end.  Tracked as #24
