### ISSUE TITLE
Name field seems missing

### ISSUE THREAD

**Issue by severinmenard** [fieldpapers/fieldpapers#191]
The ESRI shapefiles provided through this job: http://export.hotosm.org/en/exports/1dd39ab3-eb98-46ec-9146-d5d09b8be308/

do no not include the name field

**Comment by severinmenard** [comment]
actually the same for the thematic layers

**Comment by mojodna** [comment]
Do you know where the SHPs come from?  I.e. whether it's that FP isn't including it or if it's being dropped in the process.

Also, what does "thematic layers" refer to here?

**Comment by mojodna** [comment]
The CSV didn't previously include atlas and snapshot titles.  It does now.  The GeoJSON version appears to have already incorporated titles.

**Comment by mojodna** [comment]
Meant to ref https://github.com/fieldpapers/fp-web/commit/6d03c4835e458133e89156c030186f8beb0d317f

**Comment by severinmenard** [comment]
Oops sorry, this issue was for another OSM service (HOT Exports)! My apologies for disturbing

**Comment by mojodna** [comment]
No prob, it led to a fix/improvement anyway!
