### ISSUE TITLE
Automatic resizing of tool on zoom actions

### ISSUE THREAD

**Issue by smarshy** [fieldpapers/fieldpapers#192]
@mojodna @sconnelley 
Currently, the atlas tool is automatically enlarged on zooming in. A similar behavior is witnessed when zooming out .As a result, it often exceeds the viewport dimensions leading to resizing actions by the user.Why wasn't  the tool size kept constant?That would have decreased a lot of resizing loop actions by the user .

**Comment by mojodna** [comment]
This is fixed as of fieldpapers/fp-web#15.
