### ISSUE TITLE
bbox in QRcode

### ISSUE THREAD

**Issue by dalekunce** [fieldpapers/fieldpapers#194]
Add the bbox for the task area in the QR Code

**Comment by mojodna** [comment]
Append to `print_href` with `?bbox=1,2,3,4` in https://github.com/fieldpapers/fp-legacy/blob/modernize/decoder/compose.py#L36

**Comment by mojodna** [comment]
minX, minY, maxX, maxY

**Comment by mojodna** [comment]
`href` comes in via https://github.com/fieldpapers/fp-legacy/blob/modernize/decoder/compose.py#L212

Bounds should be available from the `mmap` object (which is a ModestMaps-Python instance).

**Comment by mojodna** [comment]
ModestMaps.Map uses tile coordinates + offsets to represent bounds, so it was easier to assemble the URL when `bounds` was available (and to strip it out when printing `href` as text).
