### ISSUE TITLE
Atlas page view

### ISSUE THREAD

**Issue by sconnelley** [fieldpapers/fieldpapers#20]
Need to mark-up this view in dev, [http://fieldpapers.org/atlas.php?id=pmmqscct/A1](http://fieldpapers.org/atlas.php?id=pmmqscct/A1)
New fieldpapers URL would be "/atlases/pmmqscct/A1"

**Comment by sconnelley** [comment]
After inspecting the current Atlas "page" view, it's basically the same view as an Atlas page with just the pages filtered

**Comment by mojodna** [comment]
Ah, cool.  At one point I had these routes working, but I remember you mentioning that they'd stopped before I went on vacation.  I think it was the introduction of the [`PagesController`](https://github.com/fieldpapers/fp-web/blob/master/app/controllers/pages_controller.rb) that likely caused the regression (and the obnoxiousness of the [resource member declaration](https://github.com/fieldpapers/fp-web/blob/master/config/routes.rb#L20-L28) that was necessary to simultaneously support pagination).

**Comment by mojodna** [comment]
This appears to be working, ignoring copy changes from #27 and #28 and the arguably useful presence of activity per-page.

**Comment by sconnelley** [comment]
This is done, no?

**Comment by mojodna** [comment]
Looks like it, unless there were more things you were thinking needed to be done.

**Comment by sconnelley** [comment]
seems to mirror what's currently available.  
As long as [this](https://github.com/fieldpapers/fp-web/blob/master/app/controllers/pages_controller.rb#L5) looks good to you, I say we close this issue

**Comment by mojodna** [comment]
This (might) be slightly more optimized, reference-wise.  Mind making the change and closing this?

```ruby
    @page = Page.find_by_atlas_id_and_page_number(params[:id], params[:page])
    @atlas = @page.atlas
```

**Comment by sconnelley** [comment]
not sure that is going to work.  The problem I had was last week was that `params[:id]` was a slug being passed in, so the atlas was never found.  That's why I had to find the `id` from the slug

**Comment by mojodna** [comment]
Ah, of course!  That apparently pre-dates the introduction of `friendly_id`, back when `id` _was_ the slug.

Try this on for size?

```ruby
  @atlas = Atlas.find_by_slug(params[:id])
  @page = @atlas.pages.find_by_page_number(params[:page])
```

**Comment by sconnelley** [comment]
Worked and [Done](https://github.com/fieldpapers/fp-web/commit/003afb09b869e4a9a87a919a3fcc2f7342b477b0)
