### ISSUE TITLE
Blocking bug: all the last atlas are pending

### ISSUE THREAD

**Issue by severinmenard** [fieldpapers/fieldpapers#201]
It seems something has been blocking the creation of the FP atlas for around 12 hours.

**Comment by mojodna** [comment]
Possibly also related to https://github.com/fieldpapers/fp-web/pull/13

I'm looking into it now. It looks like the web callback URLs being generated are wrong.

**Comment by mojodna** [comment]
Yup, some of the Elastic Beanstalk URL detection was leaking out and causing problems. Now fixed.
