### ISSUE TITLE
Bug: Geojson import fail? 

### ISSUE THREAD

**Issue by banmedo** [fieldpapers/fieldpapers#210]
so i was trying to import a geojson as grid to make it atlas and failed. I even used the same geojson that was exported from export as geojson.
I went through docs and didn't see it listed under "To Do" or have missed it.
Is this a known issue?

Edit: I see this
![image](https://cloud.githubusercontent.com/assets/5027933/12841217/496dab0a-cc12-11e5-9f3e-5708b8195c7f.png)

Edit 2: On the console i see this
> Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by mojodna** [comment]
This was likely fixed in either https://github.com/fieldpapers/fp-web/pull/23 or https://github.com/fieldpapers/fp-web/commit/8fdb8b68f3961b44a99509b05629b59fb28004d5

If it persists, can you reopen this issue and paste the GeoJSON you used into it?
