### ISSUE TITLE
all uploads failing

### ISSUE THREAD

**Issue by aceb694** [fieldpapers/fieldpapers#212]
Hi, 

I've tried to upload two of my marked Atlas pages including parts of Fort Dauphin, Madagascar to the Field Papers upload page (http://fieldpapers.org/snapshots/new) but after uploading successfully the process fails shortly after beginning to create the snapshot. The error message displayed says 'We're sorry, but something went wrong. If you are the application owner check the logs for more information.' The images I am working with adhere to all the rules listed on the upload page. I have tried: uploading images taken using an iPhone 5s and scanned; using black and white, and color images; using .png, .jpg, and .tiff; using 200 dpi and 250 dpi; using images oriented landscape and portrait; but nothing makes a difference. Attached are just a couple of the image files I have tried. I am running OS X 10.11 and using Chrome. Can someone check the logs to see what the specific error is?

Much appreciated,
Ben

![b2](https://cloud.githubusercontent.com/assets/10951233/13150614/8e437556-d677-11e5-9248-5e3df19fc2c0.png)

![d1](https://cloud.githubusercontent.com/assets/10951233/13150632/9e80147e-d677-11e5-8de3-6eddc2a6e279.JPG)

**Comment by mojodna** [comment]
This was the underlying fix: https://github.com/fieldpapers/fp-web/commit/f9b58d65377c945491adf887de1272d57c7c6e2f (needed to mesh with making the provider list more configurable)

Sorry 'bout that!
