### ISSUE TITLE
fp-web: Export data grid (CSV) of snapshot ids corresponding to atlas pages

### ISSUE THREAD

**Issue by mojodna** [fieldpapers/fieldpapers#217]
Match the layout of the data grid to the grid of survey areas associated with a given atlas, e.g.:

![image](https://cloud.githubusercontent.com/assets/45/13272552/e0d2b5ba-da51-11e5-9c46-572eb99a01a5.png)

When multiple snapshots exist for a given page, comma-delimit it?

/cc @DrishT

**Comment by mojodna** [comment]
Open Q: should row A contain row names and column 1 contain column numbers or can Excel (etc.) print them?

**Comment by DrishT** [comment]
Yes. I think it would be easier to print and use if the the first row and columns have the letter and number.
