### ISSUE TITLE
fp-web: Make all check box labels clickable

### ISSUE THREAD

**Issue by seav** [fieldpapers/fieldpapers#222]
For the new interface, only the "UTM Grid" check box label toggles the check box when clicked. The remaining 3 labels do not: "Print notes", "Keep atlas private", and "Pin grid to map". For usability, all labels should be clickable.

**Comment by ian-ross** [comment]
Thanks for the report, Eugene!  There's something weird going on there, because all the checkboxes have `<label>` tags with the right `for` attributes.  We'll have to investigate...

**Comment by ian-ross** [comment]
Fixed by https://github.com/fieldpapers/fp-web/pull/26.
