### ISSUE TITLE
Sample Tiles for PDF Not High Enough Zoom

### ISSUE THREAD

**Issue by hallahan** [fieldpapers/fieldpapers#226]
For the posm-carto map in Field Papers, the PDF renderer is sampling tiles at too low of a zoom level. This is causing our PDF print outs to be quite blurry. 

![screen shot 2016-03-11 at 12 16 15 pm](https://cloud.githubusercontent.com/assets/556367/13709733/75657d3c-e783-11e5-8d4e-149d619d2afd.png)

![screen shot 2016-03-11 at 12 21 33 pm](https://cloud.githubusercontent.com/assets/556367/13709809/d9d40d60-e783-11e5-8cce-40a3ef0b7dce.png)

**Comment by mojodna** [comment]
![image](https://cloud.githubusercontent.com/assets/45/13713456/07ac01ee-e797-11e5-8622-edafb020977d.png)
