### ISSUE TITLE
Edit in iD in POSM Field Papers brings you to master OSM iD

### ISSUE THREAD

**Issue by hallahan** [fieldpapers/fieldpapers#227]
We really want it to bring you to POSM iD.

![screen shot 2016-03-11 at 12 24 13 pm](https://cloud.githubusercontent.com/assets/556367/13709892/44cecc0e-e784-11e5-8e20-cc91b28981cc.png)

**Comment by mojodna** [comment]
Fixed in https://github.com/fieldpapers/fp-web/commit/78aca6f351c172e1ae92d48d4ff244f77f1cca63
