### ISSUE TITLE
All atlases are 'anonymous'

### ISSUE THREAD

**Issue by jnordling** [fieldpapers/fieldpapers#254]
I was making atlases and about half way through realized that I needed to bookmark them because my atlases were being added as anonymous and not under my username. 

I know this feature used to work when fieldpapers was PHP app. Maybe lost/broke when updated.

Just wanted to report, happy to contribute if pointed in the right direction.

**Comment by mojodna** [comment]
@jnordling are you sure you're logged in? We recently added functionality that make it easier to find atlases created while logged in.

**Comment by mojodna** [comment]
@jnordling my bad, definitely slipped by. Just deployed the fix @ranchodeluxe made.
