### ISSUE TITLE
Make page numbers on atlas detail page links

### ISSUE THREAD

**Issue by mojodna** [fieldpapers/fieldpapers#26]
(Links to the page detail page)

![image](https://cloud.githubusercontent.com/assets/45/7056369/f10f8178-ddff-11e4-98fd-9ca8bc7c5588.png)

**Comment by sconnelley** [comment]
You mean each cell should link to respective page view?

**Comment by mojodna** [comment]
That's what I was thinking.  Low prio.

**Comment by sconnelley** [comment]
done d036da52c49cb41fd7f68594334b452bcc0e26bd
