### ISSUE TITLE
BUG: Black pdf if satelite imagery is chosen as background

### ISSUE THREAD

**Issue by severinmenard** [fieldpapers/fieldpapers#262]
Eg: 
http://fieldpapers.org/atlases/mwie6kv1
http://fieldpapers.org/atlases/5thmpzi6/B2

**Comment by Nuts2001** [comment]
I'm also seeing this. Have you gotten help about it. Please help

http://fieldpapers.org/compose#16/-29.1392/27.7693

**Comment by almccon** [comment]
Seems like the same issue as #224, #139, and maybe some others.

**Comment by quincylvania** [comment]
Closing as duplicate.
