### ISSUE TITLE
Adding a custom TMS as a basemap?

### ISSUE THREAD

**Issue by d3netxer** [fieldpapers/fieldpapers#263]
Does field papers support this (see #110 )? I thought it may have been a feature. I don't see this as an option anymore when selecting a basemap

**Comment by almccon** [comment]
I think you should be able to paste a TMS template into the relevant spot, even thought it's not obvious. I can't check it myself right now though.

**Comment by d3netxer** [comment]
brilliant, that works! thaks @almccon

**Comment by d3netxer** [comment]
for anybody else who want more details on how this is done:

you have to manually paste in the basemap input field when you are making your atlas. Yes, it should be possible to edit the text in this box and paste a TMS link.

**Comment by dericke** [comment]
Pasting into this box appears to be broken in Chrome, but it worked for me in Safari.
