### ISSUE TITLE
Include page number on page detail page

### ISSUE THREAD

**Issue by mojodna** [fieldpapers/fieldpapers#27]
http://localhost:3000/atlases/79vdl2b2/A1

![image](https://cloud.githubusercontent.com/assets/45/7056404/2a700a50-de00-11e4-8c27-e09776d1e96b.png)

Probably in place of "One page" (which is incorrect).

**Comment by sconnelley** [comment]
[Done](https://github.com/fieldpapers/fp-web/commit/f6e97cd9df2dd87c2f972a97a9c9ced221dda218)
![image](https://cloud.githubusercontent.com/assets/565486/7068690/1d8bcf7a-dea2-11e4-93ef-99303abd629c.png)
