### ISSUE TITLE
Showing error while exporting GeoJSON

### ISSUE THREAD

**Issue by tasauf1980** [fieldpapers/fieldpapers#270]
Failed to export GeoJSON file ... Showing Error!

i.e: http://fieldpapers.org/atlases/2isnr4xx.geojson

**Comment by almccon** [comment]
Hi @tasauf1980. I'm not sure why that atlas is having an error.

I made a copy of the atlas here: http://fieldpapers.org/atlases/50spxcuy
and it looks like the geojson for that new atlas is working:
http://fieldpapers.org/atlases/50spxcuy.geojson

Hopefully this will work for you?

Closing this issue for now, but feel free to re-open it if you see more errors like this.

**Comment by tasauf1980** [comment]
Hi Alan,
 Thanks mate for the help. it worked fine.

Cheers!

Tasauf A Baki Billah (Ribin)
Voting Member & Member,Community Working Group,
Humanitarian OpenStreetMap Team (HOT). <http://www.hotosm.org>

Monitoring & Coordination Lead,
Bangladesh Humanitarian OpenStreetMap Operations Team (BHOOT).
Volunteer Coordinator, OSM Bangladesh Community
<https://www.facebook.com/groups/osmbd/>.

Contact: +8801741589653, +8801811516915
Skype ID: Tasauf A Baki Billah <https://secure.skype.com/portal/overview>
Website: https://tasaufribin.wordpress.com; LinkedIn:
https://linkedin.com/in/tasauf1980;
Facebook: https://www.facebook.com/tasauf.ribin; Twitter:
https://twitter.com/Tsf1980

**Comment by smit1678** [comment]
@almccon I'm seeing a number of new and older projects have this geojson error as well: 

  * http://www.fieldpapers.org/atlases/4yjej1ia
  * http://www.fieldpapers.org/atlases/686c9xlk
  * http://www.fieldpapers.org/atlases/2o7qmvcn
  * http://www.fieldpapers.org/atlases/slx8frkx

Not sure if I can provide any other input to help with debugging.
