### ISSUE TITLE
Link atlas title to atlas detail page

### ISSUE THREAD

**Issue by mojodna** [fieldpapers/fieldpapers#28]
http://localhost:3000/atlases/79vdl2b2/A1

![image](https://cloud.githubusercontent.com/assets/45/7056415/40c2df44-de00-11e4-99ac-c35705530af8.png)

(The "Untitled" text in the upper left, which should be changed to "From Untitled")

**Comment by sconnelley** [comment]
@mojodna this is a link from Atlas page view to Atlas view right?

**Comment by mojodna** [comment]
Yup.

**Comment by sconnelley** [comment]
[Done](https://github.com/fieldpapers/fp-web/commit/f6e97cd9df2dd87c2f972a97a9c9ced221dda218)

![image](https://cloud.githubusercontent.com/assets/565486/7068677/065063fc-dea2-11e4-84c7-781fed5ab894.png)
