### ISSUE TITLE
No house numbers on large maps

### ISSUE THREAD

**Issue by riccardopastocchi** [fieldpapers/fieldpapers#298]
It would be nice to be able to make a vast territory in a single pdf sheet, like the whole territory of a city, where you can see all the house numbers. Then print a large sheet of paper with a plotter that you can hang on the wall. As for example in the ambulance stations or in the municipal offices. The problem is that if you zoom in too much on the map, the civics are no longer visible.
Can it be solved? 

<img width="639" alt="Schermata 2021-02-06 alle 12 58 07" src="https://user-images.githubusercontent.com/78115599/107117818-25d74e00-687d-11eb-946d-d1755aa2001c.png">

**Comment by quincylvania** [comment]
Hi @riccardopastocchi. Field Papers is limited by the map styles provided by the OpenStreetMap community. The default style is [OSM-carto](https://github.com/gravitystorm/openstreetmap-carto), which only shows house numbers at high zooms when there is enough space. In Field Papers you can create an atlas covering a large area that may include house numbers, but they will not appear if you're trying to fit an entire city on one paper. A3 is the largest supported paper size at the moment. I'm afraid Field Papers won't work for this use case.
