### ISSUE TITLE
SSL Certificate Name Invalid - prevents tiles from showing in iD

### ISSUE THREAD

**Issue by akadouri** [fieldpapers/fieldpapers#299]
Chrome shows an "ERR_CERT_COMMON_NAME_INVALID" error in the console when trying to load the tiles from an atlas in the iD editor. I believe this issue is also present in the warnings when you load https://fieldpapers.org/.

May be related to https://github.com/fieldpapers/fieldpapers/issues/279

**Comment by quincylvania** [comment]
This seems fixed after properly configuring SSL for fieldpapers.org. We should still secure the tiles endpoint to prevent future issues (#319).

<img width="874" alt="Screenshot 2023-03-30 at 4 42 34 PM" src="https://user-images.githubusercontent.com/2046746/228959503-5b227b0c-70ec-4fb7-bdaa-c9e1d757c162.png">
