### ISSUE TITLE
Problem to upload some papers on FieldPapers 

### ISSUE THREAD

**Issue by Luarg-osm** [fieldpapers/fieldpapers#301]
Hi,
 I just would like to inform everyone that appartently is not possible to upload papers on FieldPapers, there is any way to fix it? 
I tried many times yesterday and today but it doesn't work. The .jpg is 200 dpi and the QR code is visible. 
![errore](https://user-images.githubusercontent.com/83643220/116990716-c948cb00-acd3-11eb-8a5a-c3f690fdfa85.JPG)

Thanks

**Comment by quincylvania** [comment]
@Luarg-osm Thanks for reporting. Not sure what this outage was or how long it existed, but uploading is currently working.
