### ISSUE TITLE
"Make Atlas" breaks the site

### ISSUE THREAD

**Issue by emilyrbowe** [fieldpapers/fieldpapers#302]
Hi, I just tried to make a map using the tool and get an error when I hit "Make Atlas". [This](http://fieldpapers.org/compose#16/40.6893/-73.9580) is the page I was on right before the error. 

![image](https://user-images.githubusercontent.com/7975988/117027793-08bee980-accb-11eb-8367-19bb5564e73b.png)

**Comment by jjiglesiasg** [comment]
Same happen to me today 20211108

**Comment by quincylvania** [comment]
@emilyrbowe @jjiglesiasg Thanks for reporting. Not sure what the issue was or how long it lasted, but things are working now.
