### ISSUE TITLE
Getting an "unsafe website" warning when I visit on Chrome, Safari or Firefox

### ISSUE THREAD

**Issue by aawiseman** [fieldpapers/fieldpapers#303]
In each browser I've tried I've gotten a warning I had to ignore or skip to log on. Here is Firefox for example

<img width="969" alt="Screen Shot 2021-05-21 at 2 59 54 PM" src="https://user-images.githubusercontent.com/5025092/119202273-48b0fb00-ba45-11eb-9fbc-7f9f7c7e8102.png">

**Comment by almccon** [comment]
This is probably a dupe of #299. I think we never (properly) added SSL, so you have to "accept the risk and continue" and it will work. But maybe this does result in insurmountable errors when using tiles in iD as in #299, not sure.

**Comment by quincylvania** [comment]
SSL is properly deployed now 👍

(see also #279)

https://fieldpapers.org
