### ISSUE TITLE
"We're sorry, but something went wrong." on `/compose` page

### ISSUE THREAD

**Issue by MarcinWieczorek** [fieldpapers/fieldpapers#309]
Any request to make an atlas gives me this message:
> We're sorry, but something went wrong.
>
> If you are the application owner check the logs for more information.

Thanks.

**Comment by DeBigC** [comment]
I'm just adding to the request here to press more interest down this blocked pipe - same problem as below


> Any request to make an atlas gives me this message:
> 
> > We're sorry, but something went wrong.
> > If you are the application owner check the logs for more information.
> 
> Thanks.

**Comment by almccon** [comment]
Hello @MarcinWieczorek and @DeBigC. Yes the Field Papers server got stuck sometime around the end of December. We managed to reboot the server and it seems to be working now. Sorry about that!

**Comment by MarcinWieczorek** [comment]
Thanks, it works fine now.

**Comment by DeBigC** [comment]
Im already using one of the maps, thank you
