### ISSUE TITLE
Rendering "in process" since 2 weeks

### ISSUE THREAD

**Issue by sanketgarade** [fieldpapers/fieldpapers#310]
Hello

I submitted [my render request](http://fieldpapers.org/atlases/qvvgz1iy) 2 weeks back and it's still in process. Other people's requests are also pending since a long time. Is the site down? 

I tried contacting you via email, but it bounced. Tweeted, but no response.

**Comment by almccon** [comment]
Hello @sanketgarade. Yes the Field Papers server got stuck sometime around the end of December. We managed to reboot the server and it seems to be working now. Sorry about that!

Any previous render requests will probably be stuck forever, but if you try to recreate your atlas I think it will work.
