### ISSUE TITLE
Transfer ownership to OSM US

### ISSUE THREAD

**Issue by mizmay** [fieldpapers/fieldpapers#311]
Initial steps
- [x] Add @jessbeutler @quincylvania @mcawley to this repo
- [x] Create Heroku account (@mcawley)
- [x] ~Get the main apps up and running on Heroku~ Transfer Heroku apps over to OSMUS (@quincylvania )
- [x] Re-establish / check AWS account (@mcawley)
- [x] Start a draft of public blog post (@mcawley)
- [x] Set up a follow-up meeting in 2 weeks (@mizmay )

Secondary steps
- [x] Transfer DNS (@ebrelsford)
- [x] Transfer domain (on AWS so it might just migrate when we transfer the AWS account) (@ebrelsford )
- [x] Track down and transfer ownership of social media (@almccon)
- [x] Transfer help@fieldpapers.org account (@quincylvania )

**Comment by almccon** [comment]
- [ ] Transfer Transifex project ownership. It looks like @almccon has access to https://www.transifex.com/fieldpapers and can add anyone else as a maintainer.
- [ ] Transfer ownership of help@fieldpapers.org mailing list (http://email.fieldpapers.org/ ?) 
- [ ] @fieldpapers twitter account
- [ ] tumblr.com/fieldpapers

**Comment by ebrelsford** [comment]
There is also a Google Analytics property we should move over if that's useful.

**Comment by mizmay** [comment]
- [ ] Create administrative Slack channel on OSM US for migration / related issues
- [ ]  Setting up Transifex account we can add as maintainer (@jessbeutler)
- [ ] Draft the blog post collaboratively
- [ ] Release blog post

**Comment by almccon** [comment]
I sent the login information for the twitter account to @jessbeutler.

For Tumblr, I can add anyone as an admin on that blog, I just need to know what Tumblr account you'd like to have authorized as an admin.

**Comment by quincylvania** [comment]
Are the apps already running on Heroku? It looks pretty easy to [transfer apps between teams](https://devcenter.heroku.com/articles/transferring-apps) instead of spinning up new apps separately.

**Comment by almccon** [comment]
As of today, we transferred the Heroku apps to the OSM-US Heroku organization! 🎉  Transferring the AWS account is the next big task!

**Comment by almccon** [comment]
More about the help@fieldpapers.org help email address transfer: OSM-US can just set that email up to forward to whatever addresses they want it to forward to. That can be done after the DNS and domain registrations are under their control. Right now, Stamen has that address set up as a mailing list using Mailgun but that's overkill and we should just remove that part of the process when we do the transfer. So any references to Mailgun can be removed when OSM US sets up that address to forward somewhere else.

**Comment by almccon** [comment]
I see we also have a free account on Sentry.io that monitors Field Papers and sends us an email whenever there's a server error. Generally, I ignore all those emails but they could become useful to receive if anyone ever starts to do any maintenance or improvement of FP again. I think it will be as simple as just transferring the whole Sentry account over to OSM US.

- [ ] Transfer Sentry.io account

**Comment by quincylvania** [comment]
help@fieldpapers.org now redirects to team@openstreetmap.us
