### ISSUE TITLE
Providing credit to OSM (and potentially other sources)

### ISSUE THREAD

**Issue by serialc** [fieldpapers/fieldpapers#315]
Hi,

A great resource.
Unless I'm mistaken most of the online webmaps and the generated PDF atlases do not provide **credit** for the OSM data.
It's a simple matter of adding a line of text and/or URL. 
https://www.openstreetmap.org/copyright
https://wiki.osmfoundation.org/wiki/Licence/Attribution_Guidelines

Kind regards,
Cyrille

**Comment by quincylvania** [comment]
@serialc Thanks, this is #135.
