### ISSUE TITLE
Port atlas progress interstitial

### ISSUE THREAD

**Issue by mojodna** [fieldpapers/fieldpapers#32]
To address the underlying causes of #18, I'm now updated `composed_at` when the atlas has been rendered as well as periodically updating `progress`.  This means that we can (and should) re-introduce the progress interstitial from the existing site in order to show the current status of a render.

**Comment by sconnelley** [comment]
Dummied in progress bar to track atlas rendering. [commit](https://github.com/fieldpapers/fp-web/commit/aba0de07a178b79b9e2e0e7c40ef16d8e2d17e7d)

**Comment by sconnelley** [comment]
Push it to dev site and low and behold it works.  Now need to change markup to match

**Comment by mojodna** [comment]
I love it when plan comes together.

**Comment by sconnelley** [comment]
This is functionally complete
![image](https://cloud.githubusercontent.com/assets/565486/7136648/ef4c953a-e280-11e4-9906-2d936dfe0cc3.png)
