### ISSUE TITLE
Add an Alpha banner to the site

### ISSUE THREAD

**Issue by danrademacher** [fieldpapers/fieldpapers#37]
We need a simple banner across the top of every page of the site like this:

**This is an alpha release. Note that scanning does not work yet. Atlas data will be lost on move to beta.**

**Comment by danrademacher** [comment]
@mojodna should we include a link to https://www.transifex.com/projects/p/fieldpapers/ and language to encourage translation?

**Comment by sconnelley** [comment]
[Commit](https://github.com/fieldpapers/fp-web/commit/c2e67c6f7405d84e520c1bac155c5cec0f9c1c5c)
![image](https://cloud.githubusercontent.com/assets/565486/7163871/62745e28-e36a-11e4-94bd-f23ad15bc666.png)
