### ISSUE TITLE
Convert provider select into a combo box

### ISSUE THREAD

**Issue by mojodna** [fieldpapers/fieldpapers#40]
To more easily facilitate adding custom tile sources.

A combo box implementation that requires jQuery: https://select2.github.io/examples.html#tags

**Comment by sconnelley** [comment]
![image](https://cloud.githubusercontent.com/assets/565486/7280034/31a64e08-e8ee-11e4-8860-dd558b9b695b.png)

**Comment by mojodna** [comment]
Sweet!
