### ISSUE TITLE
Map doesn't save selected layer, but layer select does

### ISSUE THREAD

**Issue by kiselev-dv** [fieldpapers/fieldpapers#45]
How to reproduce:
1. Select Black & White layer
2. Go to one of the copyright links (Stamen toner for instance)
3. Go back with browser back button

Expected result:
Last location, paper size and other parameters was saved and loaded

Result:
Layers select has saved previously selected layer, but it wasnt applyed to map.

**Comment by mojodna** [comment]
@sconnelley looks like a missing event handler?

**Comment by kiselev-dv** [comment]
Yep, if to be more precise, it's looks like wrong order in initialization sequence. 

Like select value was loaded from cookie and applied before select's onchange listener have been binded with map layer.

**Comment by sconnelley** [comment]
Was never actually pulling values from form fields on initial load, assuming they would be defaults. Will probably need to update the `layout` state as well
