### ISSUE TITLE
ActionView::Template::Error: malformed format string - %[

### ISSUE THREAD

**Issue by mojodna** [fieldpapers/fieldpapers#49]
in `app/views/shared/_footer.html.erb`

This has shown up in the `de` locale and has been triggered by GoogleBot (possibly with `de` active?).  It doesn't happen every time, so it may be related to one of the translation strings.

https://app.getsentry.com/stamen/field-papers/group/63043343/

**Comment by sconnelley** [comment]
It's a problem with translation string

![image](https://cloud.githubusercontent.com/assets/565486/7209268/076b7a3c-e515-11e4-9ace-10e0e956d6d6.png)

**Comment by sconnelley** [comment]
Should be fixed [commit](https://github.com/fieldpapers/fp-web/commit/7444443c2be0d9f65d7a4474a7dc80c64c9b08bb)
