### ISSUE TITLE
Date links from atlas archives fail

### ISSUE THREAD

**Issue by danrademacher** [fieldpapers/fieldpapers#5]
Clicking on a date here: http://stamen-fieldpapers-dev.herokuapp.com/atlases
![image](https://cloud.githubusercontent.com/assets/1423200/6455983/9fa3ba0e-c110-11e4-90c2-db412ee67ede.png)

Results in this:
http://stamen-fieldpapers-dev.herokuapp.com/atlases?month=2015-02
![image](https://cloud.githubusercontent.com/assets/1423200/6455990/b9f8708e-c110-11e4-9e03-13c37977ecf1.png)

I'd expect it to produce a gallery of atlases from that month (Feb 2015).

**Comment by mojodna** [comment]
Corresponding stack trace:

```
Mysql2::Error: Column 'created_at' in where clause is ambiguous: SELECT COUNT(DISTINCT `atlases`.`id`) FROM `atlases` LEFT OUTER JOIN `users` ON `users`.`id` = `atlases`.`user_id` WHERE (atlases.private = false) AND (CONCAT(YEAR(created_at), '-', LPAD(MONTH(created_at), 2, '0')) = '2015-02')

ActiveRecord::StatementInvalid (Mysql2::Error: Column 'created_at' in where clause is ambiguous: SELECT COUNT(DISTINCT `atlases`.`id`) FROM `atlases` LEFT OUTER JOIN `users` ON `users`.`id` = `atlases`.`user_id` WHERE (atlases.private = false) AND (CONCAT(YEAR(created_at), '-', LPAD(MONTH(created_at), 2, '0')) = '2015-02')):
   app/controllers/atlases_controller.rb:11:in `index'
```
