### ISSUE TITLE
Atlas provider field wrong?

### ISSUE THREAD

**Issue by sconnelley** [fieldpapers/fieldpapers#7]
I was expecting Atlas `provider`  to be a string not an integer.

**Comment by mojodna** [comment]
Where are you seeing this?  I agree.

**Comment by sconnelley** [comment]
Atlas page and in the database table `atlases`

**Comment by mojodna** [comment]
I'll investigate, probably tomorrow unless this is blocking you in the meantime.

**Comment by sconnelley** [comment]
no not at all, just bringing it up.

**Comment by mojodna** [comment]
@sconnelley fat-fingered a migration.  Since we're not migrating live data yet, I just fixed the migration itself, which means that you'll need to reload a dump and migrate forward.

**Comment by mojodna** [comment]
Scratch that.  The partially migrated dump I've been using had that migration baked into it, so I went ahead with forward migrations.
