### ISSUE TITLE
Rendering private atlases fails

### ISSUE THREAD

**Issue by althio** [fieldpapers/fieldpapers#85]
On http://next.fieldpapers.org/compose/describe
and choosing a Private Atlas (select the chekbox)
at later stage the rendering fails.
eg. http://next.fieldpapers.org/atlases/2qocim4h

Error message
> The page you were looking for doesn't exist.
> You may have mistyped the address or the page may have moved.
> If you are the application owner check the logs for more information.

Atlas creation with same extent and configuration - only public instead of private - is succesful.

**Comment by mojodna** [comment]
Thanks for spotting this!
