### ISSUE TITLE
Ensure that JOSM plugin works with new-style URLs

### ISSUE THREAD

**Issue by mojodna** [fieldpapers/fieldpapers#95]
..and fp-tiler

https://github.com/iandees/josm-fieldpapers
https://github.com/iandees/josm-fieldpapers/blob/master/src/org/openstreetmap/josm/plugins/fieldpapers/FieldPapersAddLayerAction.java

**Comment by mojodna** [comment]
Docs should get a run-through as well: http://wiki.openstreetmap.org/wiki/JOSM/Plugins/FieldPapers

**Comment by mojodna** [comment]
Forked to https://github.com/fieldpapers/josm-fieldpapers

**Comment by mojodna** [comment]
After cloning / symlinking the plugin under `josm/plugins` (per https://josm.openstreetmap.de/wiki/DevelopersGuide/DevelopingPlugins), I opened the whole tree in IntelliJ and added "Ant Build" settings for core and the plugins I wanted to build.  (I originally went through each of the generated project configs to ensure that they were pointing to the correct JDK and core modules, but that may not have been necessary).

**Comment by mojodna** [comment]
https://github.com/gidema/josm-openservices/blob/4fe0ad61421d2a0b993332e070b64313314f0988/src/main/java/org/openstreetmap/josm/plugins/ods/OpenDataServicesPlugin.java#L84-L115 contains code that fetches JSON from a remote source and parses it.  This is likely the simplest way to fetch metadata from FP (though it's likely to block the UI while executing).

**Comment by mataharimhairi** [comment]
@mojodna looks like you're aware of this :) tried to use the fieldpapers plugin in josm and added the scanned snapshot url required, which gives me the following response:

Could not read information for the id "http://fieldpapers.org/snapshots/2a6hry5o#12/55.9348/-3.1960" from fieldpapers.org

will this not be fixed till josm can take the new urls produced by fieldpapers snapshots, or will the urls be modified so that they are like the old ones and can be accepted by josm? tried adding the php?id= portion to the url, which didn't work.

**Comment by mojodna** [comment]
There are 2 problems:

1. the plugin needs to recognize the new-style URLs (it's theoretically possible to work around it by doing what you did and assembling an old-style URL, but (2) prevents that from working
2. the plugin current attempts to screen-scrape data from the snapshot page on fieldpapers.org and makes certain assumptions about where the tiles are hosted

(2) is the more substantial piece, but the OpenDataServicesPlugin should provide enough clues on how to do this effectively.

**Comment by mojodna** [comment]
Submitted as a PR: https://github.com/iandees/josm-fieldpapers/pull/4

**Comment by mojodna** [comment]
I've posted a JAR with these patches here:

http://data.stamen.com.s3.amazonaws.com/fieldpapers/fieldpapers-20150611.jar

Put it in either `~/.josm/plugins` (Linux) or `~/Library/JOSM/plugins` (OS X).  Not sure where it goes on Windows.

**Comment by mojodna** [comment]
The JOSM plugin registry has been updated w/ 0.3.0, so users should be prompted to upgrade either when they start, when the plugin list is updated, or when JOSM is updated.  Calling this done.
