### ISSUE TITLE
Pan does not work on atlas selection in Chrome on Windows

### ISSUE THREAD

**Issue by wonderchook** [fieldpapers/fieldpapers#97]
When selecting the area to create my Atlas the Pan button on the top left of the atlas selection window does not work when using Chrome. I have verified that it does work when using Firefox. 

My system information: 
Windows 8.1 Pro
Chrome Version 42.0.2311.135 m

**Comment by mojodna** [comment]
@sconnelley I could use your eyes on this.

The cursor changes and the draggable highlights when hovering on it, but instead of moving the selection widget, the map pans instead.  This is happening to me in Chrome 43 on Windows 8.1.

**Comment by mojodna** [comment]
Ditto on the Windows 10 preview.

Just for kicks, I tried it out in Project Spartan and the standard Leaflet controls don't even show up.

**Comment by sconnelley** [comment]
Can't replicate with:
* Chrome 43.0.2357.81
* Windows 8.1 Enterprise Evaluation

**Comment by sconnelley** [comment]
hey @mojodna how did you install `Windows 10 preview`?  I tried downloading it from http://dev.modern.ie/tools/vms/ but couldn't get Chrome to install on it

**Comment by mojodna** [comment]
I downloaded the installer from http://windows.microsoft.com/en-us/windows/preview-iso

Starting there, I was able to install Chrome.

**Comment by sconnelley** [comment]
Still can't replicate on:
* Windows 10 preview
* Chrome 43

**Comment by mojodna** [comment]
After Skyping with @sconnelley, we suspect touch events / input device driver differences (@wonderchook is using a Surface, I'm using VMware circa Windows 8, and @sconnelley is using VirtualBox).  I'm going through `leaflet-draggable-any.js` to investigate this since I can reproduce it.

**Comment by sconnelley** [comment]
@mojodna ok I think I may have it

**Comment by mojodna** [comment]
Yay!  Confirmed working in Chrome 43 on Windows 8.1 (VMware).
